"""initial schema

Revision ID: 2a71b265792c
Revises: 
Create Date: 2026-06-08 11:35:16.513716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a71b265792c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_templates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='project_status'), server_default='ACTIVE', nullable=False),
    sa.Column('repository_url', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('technologies',
    sa.Column('kind', sa.Enum('LANGUAGE', 'FRAMEWORK', 'DATABASE', 'TOOL', name='technology_kind'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'slug', name='uq_technologies_kind_slug')
    )
    op.create_table('artifact_types',
    sa.Column('scope', sa.Enum('GLOBAL', 'PROJECT', name='scope_kind'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('output_files', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'GLOBAL' AND project_id IS NULL) OR (scope = 'PROJECT' AND project_id IS NOT NULL)", name='ck_artifact_types_scope_project'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_artifact_types_global_slug', 'artifact_types', ['slug'], unique=True, postgresql_where=sa.text('project_id IS NULL'))
    op.create_index('uq_artifact_types_project_slug', 'artifact_types', ['project_id', 'slug'], unique=True, postgresql_where=sa.text('project_id IS NOT NULL'))
    op.create_table('domains',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ubiquitous_language', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'slug', name='uq_domains_project_slug')
    )
    op.create_table('project_technologies',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'technology_id')
    )
    op.create_table('skills',
    sa.Column('scope', sa.Enum('GLOBAL', 'PROJECT', name='scope_kind'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'GLOBAL' AND project_id IS NULL) OR (scope = 'PROJECT' AND project_id IS NOT NULL)", name='ck_skills_scope_project'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skills_tags', 'skills', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('uq_skills_global_slug', 'skills', ['slug'], unique=True, postgresql_where=sa.text('project_id IS NULL'))
    op.create_index('uq_skills_project_slug', 'skills', ['project_id', 'slug'], unique=True, postgresql_where=sa.text('project_id IS NOT NULL'))
    op.create_table('artifacts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ARCHIVED', name='artifact_status'), server_default='DRAFT', nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_type_id'], ['artifact_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_version_id'], ['artifact_versions.id'], name='fk_artifacts_current_version', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'slug', name='uq_artifacts_project_slug')
    )
    op.create_table('documents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(extracted_text, ''))", persisted=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_project_id', 'documents', ['project_id'], unique=False)
    op.create_index('ix_documents_search_tsv', 'documents', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_documents_tags', 'documents', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('notes',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('REQUIREMENT', 'CONSTRAINT', 'DECISION', 'QUESTION', 'SNIPPET', 'REFERENCE', name='note_type'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(content, ''))", persisted=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_project_id', 'notes', ['project_id'], unique=False)
    op.create_index('ix_notes_search_tsv', 'notes', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_notes_tags', 'notes', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('project_skills',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'skill_id')
    )
    op.create_table('tasks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='task_status'), server_default='TODO', nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='task_priority'), server_default='MEDIUM', nullable=False),
    sa.Column('depends_on', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_depends_on', 'tasks', ['depends_on'], unique=False, postgresql_using='gin')
    op.create_index('ix_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_tags', 'tasks', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('artifact_versions',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_note_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('source_task_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('source_document_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'version_number', name='uq_artifact_versions_number')
    )
    op.create_index('ix_artifact_versions_source_note_ids', 'artifact_versions', ['source_note_ids'], unique=False, postgresql_using='gin')
    op.create_index('ix_artifact_versions_source_task_ids', 'artifact_versions', ['source_task_ids'], unique=False, postgresql_using='gin')
    op.create_table('artifact_files',
    sa.Column('artifact_version_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(path, '') || ' ' || coalesce(content, ''))", persisted=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifact_files_search_tsv', 'artifact_files', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_artifact_files_version_id', 'artifact_files', ['artifact_version_id'], unique=False)
    op.create_table('artifact_phases',
    sa.Column('artifact_version_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', name='phase_status'), server_default='PENDING', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # The artifacts <-> artifact_versions circular FK is declared use_alter on the
    # model; op.create_table does not emit it, so add it explicitly here once both
    # tables exist.
    op.create_foreign_key(
        'fk_artifacts_current_version',
        'artifacts',
        'artifact_versions',
        ['current_version_id'],
        ['id'],
        ondelete='SET NULL',
    )

    _seed(op)


# --- Seed data (canonical technologies + built-in default artifact type) -----

_TECHNOLOGIES = [
    ('LANGUAGE', 'Python', 'python'),
    ('LANGUAGE', 'TypeScript', 'typescript'),
    ('LANGUAGE', 'JavaScript', 'javascript'),
    ('LANGUAGE', 'Go', 'go'),
    ('LANGUAGE', 'Rust', 'rust'),
    ('LANGUAGE', 'Java', 'java'),
    ('LANGUAGE', 'PHP', 'php'),
    ('LANGUAGE', 'Ruby', 'ruby'),
    ('LANGUAGE', 'C#', 'csharp'),
    ('LANGUAGE', 'Swift', 'swift'),
    ('LANGUAGE', 'Kotlin', 'kotlin'),
    ('FRAMEWORK', 'Next.js', 'nextjs'),
    ('FRAMEWORK', 'React', 'react'),
    ('FRAMEWORK', 'Vue.js', 'vuejs'),
    ('FRAMEWORK', 'Nuxt', 'nuxt'),
    ('FRAMEWORK', 'FastAPI', 'fastapi'),
    ('FRAMEWORK', 'Django', 'django'),
    ('FRAMEWORK', 'Flask', 'flask'),
    ('FRAMEWORK', 'Laravel', 'laravel'),
    ('FRAMEWORK', 'Spring Boot', 'spring-boot'),
    ('FRAMEWORK', 'Express', 'express'),
    ('FRAMEWORK', 'NestJS', 'nestjs'),
    ('FRAMEWORK', 'Ruby on Rails', 'rails'),
    ('DATABASE', 'PostgreSQL', 'postgresql'),
    ('DATABASE', 'MySQL', 'mysql'),
    ('DATABASE', 'SQLite', 'sqlite'),
    ('DATABASE', 'MongoDB', 'mongodb'),
    ('DATABASE', 'Redis', 'redis'),
    ('DATABASE', 'Qdrant', 'qdrant'),
    ('DATABASE', 'Elasticsearch', 'elasticsearch'),
    ('TOOL', 'Docker', 'docker'),
    ('TOOL', 'Kubernetes', 'kubernetes'),
    ('TOOL', 'Git', 'git'),
    ('TOOL', 'Alembic', 'alembic'),
]

_DEFAULT_ARTIFACT_TYPE_INSTRUCTIONS = """\
# Development Plan

Generate a phased, agent-executable implementation plan from the collected
project context (notes, tasks, documents, skills).

Guidelines:
- Open with an **Objective** summarizing what is being built.
- Break work into ordered **phases**; each phase has a goal, concrete tasks,
  and explicit **done criteria**.
- Respect task dependencies (`depends_on`) when ordering work.
- Surface constraints and decisions captured in notes.
- Prefer explicit, readable steps over framework magic. Apply YAGNI / DRY / KISS.
"""

_DEFAULT_ARTIFACT_TYPE_OUTPUT_FILES = (
    '[{"path": "IMPLEMENTATION_PLAN.md", '
    '"note": "Phased implementation plan: objective, phases with tasks and done criteria"}]'
)


def _seed(op) -> None:
    conn = op.get_bind()
    # Enum-typed `kind` casts cleanly from a text literal, so insert via VALUES.
    rows = ", ".join(f"('{kind}', '{name}', '{slug}')" for kind, name, slug in _TECHNOLOGIES)
    conn.execute(
        sa.text(
            f"INSERT INTO technologies (kind, name, slug) VALUES {rows} "
            "ON CONFLICT (kind, slug) DO NOTHING"
        )
    )

    conn.execute(
        sa.text(
            "INSERT INTO artifact_types "
            "(scope, project_id, name, slug, description, instructions, output_files, is_default) "
            "VALUES ('GLOBAL', NULL, :name, :slug, :description, :instructions, "
            "CAST(:output_files AS jsonb), true) "
            "ON CONFLICT (slug) WHERE project_id IS NULL DO NOTHING"
        ),
        {
            "name": "Development Plan",
            "slug": "development-plan",
            "description": "The built-in default: a phased, agent-executable implementation plan.",
            "instructions": _DEFAULT_ARTIFACT_TYPE_INSTRUCTIONS,
            "output_files": _DEFAULT_ARTIFACT_TYPE_OUTPUT_FILES,
        },
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the circular FK first so the tables can be dropped (idempotent).
    op.execute("ALTER TABLE artifacts DROP CONSTRAINT IF EXISTS fk_artifacts_current_version")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifact_phases')
    op.drop_index('ix_artifact_files_version_id', table_name='artifact_files')
    op.drop_index('ix_artifact_files_search_tsv', table_name='artifact_files', postgresql_using='gin')
    op.drop_table('artifact_files')
    op.drop_index('ix_artifact_versions_source_task_ids', table_name='artifact_versions', postgresql_using='gin')
    op.drop_index('ix_artifact_versions_source_note_ids', table_name='artifact_versions', postgresql_using='gin')
    op.drop_table('artifact_versions')
    op.drop_index('ix_tasks_tags', table_name='tasks', postgresql_using='gin')
    op.drop_index('ix_tasks_project_id', table_name='tasks')
    op.drop_index('ix_tasks_depends_on', table_name='tasks', postgresql_using='gin')
    op.drop_table('tasks')
    op.drop_table('project_skills')
    op.drop_index('ix_notes_tags', table_name='notes', postgresql_using='gin')
    op.drop_index('ix_notes_search_tsv', table_name='notes', postgresql_using='gin')
    op.drop_index('ix_notes_project_id', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_documents_tags', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_search_tsv', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_project_id', table_name='documents')
    op.drop_table('documents')
    op.drop_table('artifacts')
    op.drop_index('uq_skills_project_slug', table_name='skills', postgresql_where=sa.text('project_id IS NOT NULL'))
    op.drop_index('uq_skills_global_slug', table_name='skills', postgresql_where=sa.text('project_id IS NULL'))
    op.drop_index('ix_skills_tags', table_name='skills', postgresql_using='gin')
    op.drop_table('skills')
    op.drop_table('project_technologies')
    op.drop_table('domains')
    op.drop_index('uq_artifact_types_project_slug', table_name='artifact_types', postgresql_where=sa.text('project_id IS NOT NULL'))
    op.drop_index('uq_artifact_types_global_slug', table_name='artifact_types', postgresql_where=sa.text('project_id IS NULL'))
    op.drop_table('artifact_types')
    op.drop_table('technologies')
    op.drop_table('projects')
    op.drop_table('project_templates')
    # ### end Alembic commands ###

    # Native enum types are not auto-dropped with their tables; drop them so the
    # migration is cleanly reversible and re-appliable.
    for enum_name in (
        'technology_kind',
        'project_status',
        'note_type',
        'task_status',
        'task_priority',
        'scope_kind',
        'artifact_status',
        'phase_status',
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
