"""Repository interfaces (Protocols).

Application services depend on these abstractions, not on SQLAlchemy. The
infrastructure layer provides concrete implementations. Methods exchange domain
entities / read models and primitives only — never ORM objects or Pydantic DTOs.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Protocol

from app.domain.entities import (
    Artifact,
    ArtifactFile,
    ArtifactPhase,
    ArtifactType,
    ArtifactVersion,
    Document,
    Domain,
    Note,
    NoteTypeEntity,
    Project,
    ProjectTemplate,
    Skill,
    Task,
    Technology,
)
from app.domain.enums import (
    ArtifactStatus,
    ProjectStatus,
    ScopeKind,
    TaskPriority,
    TaskStatus,
    TechnologyKind,
)
from app.domain.read_models import ProjectDetail, ProjectTechnologyRef
from app.domain.search import IndexableFile


class ProjectRepository(Protocol):
    def add(self, project: Project) -> Project: ...
    def get_by_id(self, project_id: uuid.UUID) -> Project | None: ...
    def get_by_slug(self, slug: str) -> Project | None: ...
    def get_detail_by_slug(self, slug: str) -> ProjectDetail | None: ...
    def update(self, project: Project) -> Project: ...
    def delete(self, project_id: uuid.UUID) -> None: ...
    def slug_exists(self, slug: str) -> bool: ...
    def list(
        self,
        *,
        search: str | None = None,
        language: str | None = None,
        framework: str | None = None,
        database: str | None = None,
        status: ProjectStatus | None = None,
    ) -> list[ProjectDetail]: ...
    def attach_technology(
        self, project_id: uuid.UUID, technology_id: uuid.UUID, version: str | None
    ) -> None: ...
    def detach_technology(self, project_id: uuid.UUID, technology_id: uuid.UUID) -> None: ...
    def list_technologies(self, project_id: uuid.UUID) -> list[ProjectTechnologyRef]: ...


class TechnologyRepository(Protocol):
    def add(self, technology: Technology) -> Technology: ...
    def get_by_id(self, technology_id: uuid.UUID) -> Technology | None: ...
    def find_by_kind_name(self, kind: TechnologyKind, name: str) -> Technology | None: ...
    def slug_exists(self, kind: TechnologyKind, slug: str) -> bool: ...
    def list(self, *, kind: TechnologyKind | None = None) -> list[Technology]: ...


class DomainRepository(Protocol):
    def add(self, domain: Domain) -> Domain: ...
    def get_by_id(self, domain_id: uuid.UUID) -> Domain | None: ...
    def get_by_slug(self, project_id: uuid.UUID, slug: str) -> Domain | None: ...
    def list(self, project_id: uuid.UUID) -> list[Domain]: ...
    def update(self, domain: Domain) -> Domain: ...
    def delete(self, domain_id: uuid.UUID) -> None: ...
    def slug_exists(self, project_id: uuid.UUID, slug: str) -> bool: ...


class NoteRepository(Protocol):
    def add(self, note: Note) -> Note: ...
    def get_by_id(self, note_id: uuid.UUID) -> Note | None: ...
    def update(self, note: Note) -> Note: ...
    def delete(self, note_id: uuid.UUID) -> None: ...
    def list_all(self) -> list[Note]: ...
    def list(
        self,
        project_id: uuid.UUID,
        *,
        domain_id: uuid.UUID | None = None,
        note_type_id: uuid.UUID | None = None,
        tag: str | None = None,
    ) -> list[Note]: ...


class TaskRepository(Protocol):
    def add(self, task: Task) -> Task: ...
    def get_by_id(self, task_id: uuid.UUID) -> Task | None: ...
    def get_many(self, task_ids: list[uuid.UUID]) -> list[Task]: ...
    def list_all_for_project(self, project_id: uuid.UUID) -> list[Task]: ...
    def update(self, task: Task) -> Task: ...
    def delete(self, task_id: uuid.UUID) -> None: ...
    def list(
        self,
        project_id: uuid.UUID,
        *,
        domain_id: uuid.UUID | None = None,
        status: TaskStatus | None = None,
        priority: TaskPriority | None = None,
        tag: str | None = None,
    ) -> list[Task]: ...


class NoteTypeRepository(Protocol):
    def add(self, note_type: NoteTypeEntity) -> NoteTypeEntity: ...
    def get_by_id(self, type_id: uuid.UUID) -> NoteTypeEntity | None: ...
    def get_by_slug(self, slug: str, project_id: uuid.UUID | None) -> NoteTypeEntity | None: ...
    def resolve(self, value: str, project_id: uuid.UUID) -> NoteTypeEntity | None: ...
    def list(self, *, scope: ScopeKind | None = None) -> list[NoteTypeEntity]: ...
    def list_applicable(self, project_id: uuid.UUID) -> list[NoteTypeEntity]: ...
    def update(self, note_type: NoteTypeEntity) -> NoteTypeEntity: ...
    def delete(self, type_id: uuid.UUID) -> None: ...
    def slug_exists(self, slug: str, project_id: uuid.UUID | None) -> bool: ...


class ArtifactTypeRepository(Protocol):
    def add(self, artifact_type: ArtifactType) -> ArtifactType: ...
    def get_by_id(self, type_id: uuid.UUID) -> ArtifactType | None: ...
    def get_by_slug(self, slug: str, project_id: uuid.UUID | None) -> ArtifactType | None: ...
    def list(self, *, scope: ScopeKind | None = None) -> list[ArtifactType]: ...
    def list_applicable(self, project_id: uuid.UUID) -> list[ArtifactType]: ...
    def update(self, artifact_type: ArtifactType) -> ArtifactType: ...
    def delete(self, type_id: uuid.UUID) -> None: ...
    def slug_exists(self, slug: str, project_id: uuid.UUID | None) -> bool: ...


class ArtifactRepository(Protocol):
    def add(self, artifact: Artifact) -> Artifact: ...
    def get_by_id(self, artifact_id: uuid.UUID) -> Artifact | None: ...
    def get_by_slug(self, project_id: uuid.UUID, slug: str) -> Artifact | None: ...
    def update(self, artifact: Artifact) -> Artifact: ...
    def delete(self, artifact_id: uuid.UUID) -> None: ...
    def set_current_version(self, artifact_id: uuid.UUID, version_id: uuid.UUID) -> None: ...
    def list(
        self, project_id: uuid.UUID, *, artifact_type_id: uuid.UUID | None = None
    ) -> list[Artifact]: ...
    # versions / files / phases
    def add_version(self, version: ArtifactVersion) -> ArtifactVersion: ...
    def next_version_number(self, artifact_id: uuid.UUID) -> int: ...
    def list_versions(self, artifact_id: uuid.UUID) -> list[ArtifactVersion]: ...
    def get_version(
        self, artifact_id: uuid.UUID, version_number: int
    ) -> ArtifactVersion | None: ...
    def get_version_by_id(self, version_id: uuid.UUID) -> ArtifactVersion | None: ...
    def add_files(self, files: list[ArtifactFile]) -> list[ArtifactFile]: ...
    def list_files(self, version_id: uuid.UUID) -> list[ArtifactFile]: ...
    def add_phases(self, phases: list[ArtifactPhase]) -> list[ArtifactPhase]: ...
    def list_phases(self, version_id: uuid.UUID) -> list[ArtifactPhase]: ...
    def get_phase(self, phase_id: uuid.UUID) -> ArtifactPhase | None: ...
    def update_phase(self, phase: ArtifactPhase) -> ArtifactPhase: ...
    # reverse lookups
    def list_by_source_note(self, note_id: uuid.UUID) -> list[Artifact]: ...
    def list_by_source_task(self, task_id: uuid.UUID) -> list[Artifact]: ...
    def iter_indexable_files(self) -> list[IndexableFile]: ...


class SkillRepository(Protocol):
    def add(self, skill: Skill) -> Skill: ...
    def get_by_id(self, skill_id: uuid.UUID) -> Skill | None: ...
    def get_by_slug(self, slug: str, project_id: uuid.UUID | None) -> Skill | None: ...
    def update(self, skill: Skill) -> Skill: ...
    def delete(self, skill_id: uuid.UUID) -> None: ...
    def slug_exists(self, slug: str, project_id: uuid.UUID | None) -> bool: ...
    def list(
        self, *, scope: ScopeKind | None = None, tag: str | None = None
    ) -> list[Skill]: ...
    def list_applicable(self, project_id: uuid.UUID) -> list[Skill]: ...
    def attach(self, project_id: uuid.UUID, skill_id: uuid.UUID) -> None: ...
    def detach(self, project_id: uuid.UUID, skill_id: uuid.UUID) -> None: ...
    def is_attached(self, project_id: uuid.UUID, skill_id: uuid.UUID) -> bool: ...


class DocumentRepository(Protocol):
    def add(self, document: Document) -> Document: ...
    def get_by_id(self, document_id: uuid.UUID) -> Document | None: ...
    def list_all(self) -> list[Document]: ...
    def set_indexed(self, document_id: uuid.UUID, indexed_at: datetime) -> None: ...
    def delete(self, document_id: uuid.UUID) -> None: ...
    def list(
        self,
        project_id: uuid.UUID,
        *,
        domain_id: uuid.UUID | None = None,
        tag: str | None = None,
    ) -> list[Document]: ...


class ProjectTemplateRepository(Protocol):
    def add(self, template: ProjectTemplate) -> ProjectTemplate: ...
    def get_by_id(self, template_id: uuid.UUID) -> ProjectTemplate | None: ...
    def get_by_slug(self, slug: str) -> ProjectTemplate | None: ...
    def list(self) -> list[ProjectTemplate]: ...
    def update(self, template: ProjectTemplate) -> ProjectTemplate: ...
    def delete(self, template_id: uuid.UUID) -> None: ...
    def slug_exists(self, slug: str) -> bool: ...


__all__ = [
    "ProjectRepository",
    "TechnologyRepository",
    "DomainRepository",
    "NoteRepository",
    "TaskRepository",
    "NoteTypeRepository",
    "ArtifactTypeRepository",
    "ArtifactRepository",
    "SkillRepository",
    "DocumentRepository",
    "ProjectTemplateRepository",
    "ArtifactStatus",
]
